SELECT DISTINCT
    ALU.PES_ID as pes_id,
    APC_ID as apc_id,
    REPLACE(APR_NOTEXI,',','.') as nota_atual
FROM TB_PESSOA ALU
    INNER JOIN TB_INGRESSO ON (ING_PESID = ALU.PES_ID)
    INNER JOIN TB_MESTRE_ALUNO ON (MAL_INGID = ING_ID)
    INNER JOIN TB_MESTRE_DISCIPLINA ON (MDI_MALID = MAL_ID)
    INNER JOIN TB_TURMA_DISCIP ttd ON (TDI_TURDISID = MDI_TURDISID)
    INNER JOIN TB_AVAPAR_FORMULA ON (TDI_TURDISID = APF_TDIID)
    INNER JOIN TB_PADRONIZACAO_DIS ON (TDI_PDIID = PDI_ID)
    INNER JOIN TB_PADDIS_TIPNOT tpt ON (TNP_PDIID = PDI_ID)
    LEFT JOIN TB_HISTORICO ON (HIS_MDIID = MDI_ID AND HIS_TNPID = TNP_ID)
    INNER JOIN TB_AVAPAR_CADAVA tac ON (APC_TDIID = TDI_TURDISID AND APC_TNPID = TNP_ID)
    LEFT JOIN TB_AVAPAR_REGNOT tar ON (APR_APCID = APC_ID AND HIS_ID = APR_HISID)
    INNER JOIN TB_DISCIPLINA td ON (DIS_DISID = TDI_DISCID)
    INNER JOIN TB_TURMA tt ON (tt.TUR_ID = ttd.TDI_TURID)
    INNER JOIN TB_CURSO tc ON (tc.CUR_ID = tt.TUR_CURID)
    INNER JOIN TB_PERIODO_LETIVO tpl ON (PEL_PERID = tt.TUR_PERID)
WHERE
    tpl.PEL_ANOREF = %s --ano do periodo letivo
    AND tt.TUR_CODTUR = %s --codigo da turma
    AND ALU.PES_CODTEL = %s --codigo do aluno RA
    and td.DIS_DESDIS = %s --nome da disciplina
    AND tpt.TNP_DESCRI = %s --indentificação do bimestre
