DECLARE @media_final INT = %s
DECLARE @ing_id INT = %s
DECLARE @dis_id INT = %s
DECLARE @cod_turma VARCHAR(30) = %s
DECLARE @tipo_nota VARCHAR(2) = 'MF'
DECLARE @user_alt VARCHAR(30)= 'integracao_vestibulare'

DECLARE @mdi_id INT = (
	SELECT MDI_ID
	FROM
		TB_PESSOA PES
		INNER JOIN TB_INGRESSO ti ON (PES_ID = ING_PESID)
		INNER JOIN TB_MESTRE_ALUNO MAL ON (ING_ID = MAL_INGID)
		INNER JOIN TB_MESTRE_DISCIPLINA ON (MAL_ID = MDI_MALID)
		LEFT OUTER JOIN TB_HISTORICO HIS ON (MDI_ID = HIS_MDIID)
		INNER JOIN TB_PADDIS_TIPNOT tpt ON (HIS_TNPID = TNP_ID)
		INNER JOIN TB_TURMA_DISCIP ON (MDI_TURDISID = TDI_TURDISID)
		INNER JOIN TB_TURMA tt ON (MAL_TURID = TUR_ID)
		INNER JOIN TB_DISCIPLINA td ON (TDI_DISCID = DIS_DISID)
		INNER JOIN TB_CURSO ON (TUR_CURID = CUR_ID)
		INNER JOIN TB_PERIODO_LETIVO ON (TUR_PERID = PEL_PERID)
	WHERE
	    ti.ING_ID = @ing_id
	    AND tt.TUR_CODTUR = @cod_turma
	    AND td.DIS_DISID = @dis_id
	    AND tpt.TNP_CODNOT = @tipo_nota
)

--Atualiza a média final do aluno com nota que veio da vestibulare
UPDATE HIS
SET
    HIS.HIS_NOTA = @media_final,
    HIS.HIS_NOTEXI = REPLACE(CAST(@media_final AS VARCHAR), '.', ','),
    HIS.USUARIO_ULT_ALTERACAO = @user_alt,
    HIS.DATA_ULT_ALTERACAO = GETDATE()
FROM
	TB_HISTORICO HIS
	INNER JOIN TB_PADDIS_TIPNOT tpt ON (HIS_TNPID = TNP_ID)
WHERE
    HIS.HIS_MDIID = @mdi_id
    AND tpt.TNP_CODNOT = @tipo_nota
