SELECT
	tp.PES_CODTEL as ra
FROM
	TB_PESSOA tp
	INNER JOIN TB_INGRESSO ti ON tp.PES_ID = ti.ING_PESID
	INNER JOIN TB_MESTRE_ALUNO tma ON ti.ING_ID = tma.MAL_INGID
	INNER JOIN TB_TURMA tt ON tma.MAL_TURID = tt.TUR_ID
	INNER JOIN TB_PERIODO_LETIVO tpl ON tt.TUR_PERID = tpl.PEL_PERID
WHERE
	tpl.PEL_ANOREF = %s
	AND tt.TUR_CODTUR = %s
	AND tma.MAL_SITMAT IN ('ATIVO')