DECLARE @total_falta INT = %s
DECLARE @ing_id INT = %s
DECLARE @bimestre VARCHAR(2) = %s
DECLARE @cod_turma VARCHAR(30) = %s
DECLARE @user_alt VARCHAR(30)= 'integracao_vestibulare'

DECLARE @mdi_id INT = (
	SELECT TOP 1
	    MDI_ID
	FROM
		TB_PESSOA PES
		INNER JOIN TB_INGRESSO ti ON (PES_ID = ING_PESID)
		INNER JOIN TB_MESTRE_ALUNO MAL ON (ING_ID = MAL_INGID)
		INNER JOIN TB_MESTRE_DISCIPLINA ON (MAL_ID = MDI_MALID)
		LEFT OUTER JOIN TB_HISTORICO HIS ON (MDI_ID = HIS_MDIID)
		INNER JOIN TB_PADDIS_TIPNOT tpt ON (HIS_TNPID = TNP_ID)
		INNER JOIN TB_TURMA_DISCIP ON (MDI_TURDISID = TDI_TURDISID)
		INNER JOIN TB_TURMA tt ON (MAL_TURID = TUR_ID)
		INNER JOIN TB_DISCIPLINA td ON (TDI_DISCID = DIS_DISID)
		INNER JOIN TB_CURSO ON (TUR_CURID = CUR_ID)
		INNER JOIN TB_PERIODO_LETIVO ON (TUR_PERID = PEL_PERID)
	WHERE
	    ti.ING_ID = @ing_id
	    AND tt.TUR_CODTUR = @cod_turma
	    AND tpt.TNP_CODNOT = @bimestre
)

--Atualiza o total de faltas na disciplina
UPDATE tmd
SET
    MDI_TOTFAL = @total_falta,
    tmd.USUARIO_ULT_ALTERACAO = @user_alt,
    tmd.DATA_ULT_ALTERACAO = GETDATE()
FROM
    TB_MESTRE_DISCIPLINA tmd
WHERE
    tmd.MDI_ID = @mdi_id